import math
import struct
import os

def calc_normal(v1, v2, v3):
    ax, ay, az = v2[0] - v1[0], v2[1] - v1[1], v2[2] - v1[2]
    bx, by, bz = v3[0] - v1[0], v3[1] - v1[1], v3[2] - v1[2]
    nx = ay * bz - az * by
    ny = az * bx - ax * bz
    nz = ax * by - ay * bx
    length = math.sqrt(nx*nx + ny*ny + nz*nz)
    if length > 0:
        return (nx/length, ny/length, nz/length)
    return (0.0, 0.0, 1.0)

class STLMesh:
    def __init__(self, name="mesh"):
        self.name = name
        self.triangles = []

    def add_triangle(self, v1, v2, v3):
        normal = calc_normal(v1, v2, v3)
        self.triangles.append((normal, v1, v2, v3))

    def add_quad(self, v1, v2, v3, v4):
        self.add_triangle(v1, v2, v3)
        self.add_triangle(v1, v3, v4)

    def add_box(self, cx, cy, cz, dx, dy, dz):
        x0, x1 = cx - dx/2, cx + dx/2
        y0, y1 = cy - dy/2, cy + dy/2
        z0, z1 = cz - dz/2, cz + dz/2

        v000 = (x0, y0, z0); v100 = (x1, y0, z0); v110 = (x1, y1, z0); v010 = (x0, y1, z0)
        v001 = (x0, y0, z1); v101 = (x1, y0, z1); v111 = (x1, y1, z1); v011 = (x0, y1, z1)

        self.add_quad(v000, v010, v110, v100) # Bottom
        self.add_quad(v001, v101, v111, v011) # Top
        self.add_quad(v000, v100, v101, v001) # Front (-Y)
        self.add_quad(v010, v011, v111, v110) # Back (+Y)
        self.add_quad(v000, v001, v011, v010) # Left (-X)
        self.add_quad(v100, v110, v111, v101) # Right (+X)

    def add_cylinder(self, cx, cy, z_bottom, z_top, radius, segments=32):
        angles = [i * 2 * math.pi / segments for i in range(segments)]
        bot_pts = [(cx + radius * math.cos(a), cy + radius * math.sin(a), z_bottom) for a in angles]
        top_pts = [(cx + radius * math.cos(a), cy + radius * math.sin(a), z_top) for a in angles]
        
        bot_center = (cx, cy, z_bottom)
        top_center = (cx, cy, z_top)

        for i in range(segments):
            next_i = (i + 1) % segments
            self.add_triangle(bot_center, bot_pts[next_i], bot_pts[i])
            self.add_triangle(top_center, top_pts[i], top_pts[next_i])
            self.add_quad(bot_pts[i], bot_pts[next_i], top_pts[next_i], top_pts[i])

    def add_bottom_plate_with_cutouts(self, radius=100.0, thickness=4.0, slot_x_inner=55.0, slot_y_width=76.0, segments=64):
        """
        Creates a bottom chassis plate with wide rectangular wheel cutouts on Left (-X) and Right (+X).
        Slot Width in Y (front-to-back): 76mm (Y from -38 to +38)
        Slot Inner Boundary in X: X = 55mm to 105mm (Depth 50mm)
        This ensures 100% zero collision with 65mm diameter, 25mm wide wheels.
        """
        half_w = slot_y_width / 2.0 # 38mm
        contour = []

        # Top Arc (from angle_right_top to angle_left_top)
        ang_right_top = math.asin(half_w / radius) # ~22.3 deg
        ang_left_top = math.pi - ang_right_top      # ~157.7 deg

        # 1. Top Arc points
        arc_steps = 32
        for i in range(arc_steps + 1):
            ang = ang_right_top + i * (ang_left_top - ang_right_top) / arc_steps
            contour.append((radius * math.cos(ang), radius * math.sin(ang)))

        # 2. Left Slot Inset
        contour.append((-slot_x_inner, half_w))  # Inward to X=-55, Y=38
        contour.append((-slot_x_inner, -half_w)) # Down to X=-55, Y=-38

        # 3. Bottom Arc points
        ang_left_bot = math.pi + ang_right_top
        ang_right_bot = 2 * math.pi - ang_right_top
        for i in range(arc_steps + 1):
            ang = ang_left_bot + i * (ang_right_bot - ang_left_bot) / arc_steps
            contour.append((radius * math.cos(ang), radius * math.sin(ang)))

        # 4. Right Slot Inset
        contour.append((slot_x_inner, -half_w)) # Inward to X=55, Y=-38
        contour.append((slot_x_inner, half_w))  # Up to X=55, Y=38

        # Extrude 2D Contour to 3D STL Mesh
        num_pts = len(contour)
        bot_pts = [(x, y, 0.0) for x, y in contour]
        top_pts = [(x, y, thickness) for x, y in contour]
        bot_center = (0.0, 0.0, 0.0)
        top_center = (0.0, 0.0, thickness)

        for i in range(num_pts):
            next_i = (i + 1) % num_pts
            self.add_triangle(bot_center, bot_pts[next_i], bot_pts[i])
            self.add_triangle(top_center, top_pts[i], top_pts[next_i])
            self.add_quad(bot_pts[i], bot_pts[next_i], top_pts[next_i], top_pts[i])

    def write_stl(self, filepath):
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, 'wb') as f:
            header = f"Binary STL Generated by Antigravity Robot Designer - {self.name}".ljust(80)[:80]
            f.write(header.encode('ascii'))
            f.write(struct.pack('<I', len(self.triangles)))
            for normal, v1, v2, v3 in self.triangles:
                f.write(struct.pack('<fff', *normal))
                f.write(struct.pack('<fff', *v1))
                f.write(struct.pack('<fff', *v2))
                f.write(struct.pack('<fff', *v3))
                f.write(struct.pack('<H', 0))

print("Regenerating STL models with ZERO-COLLISION Wheel Cutouts (76mm x 50mm slots)...")

# 1. Bottom Chassis Plate with Wide Cutouts
bottom_mesh = STLMesh("Chassis_Bottom")
bottom_mesh.add_bottom_plate_with_cutouts(radius=100.0, thickness=4.0, slot_x_inner=55.0, slot_y_width=76.0)

# Battery Tray (Center)
bottom_mesh.add_box(cx=0, cy=0, cz=6, dx=78, dy=4, dz=8)
bottom_mesh.add_box(cx=0, cy=-45, cz=6, dx=78, dy=4, dz=8)

bottom_mesh.write_stl("stl_files/chassis_bottom.stl")

# 2. Top Chassis Plate
top_mesh = STLMesh("Chassis_Top")
top_mesh.add_cylinder(0, 0, 0, 4.0, 100.0, segments=64)
top_mesh.write_stl("stl_files/chassis_top.stl")

# 3. Motor Holder
motor_mesh = STLMesh("Motor_Holder")
motor_mesh.add_box(cx=0, cy=0, cz=2, dx=40, dy=30, dz=4)
motor_mesh.add_box(cx=0, cy=0, cz=16, dx=40, dy=10, dz=24)
motor_mesh.add_cylinder(cx=0, cy=0, z_bottom=4, z_top=28, radius=13.0, segments=32)
motor_mesh.write_stl("stl_files/motor_holder.stl")

# 4. LiDAR Mount
lidar_mesh = STLMesh("LiDAR_Mount")
lidar_mesh.add_box(cx=0, cy=0, cz=2, dx=70, dy=70, dz=4)
for lx, ly in [(-25,-25), (25,-25), (-25,25), (25,25)]:
    lidar_mesh.add_cylinder(lx, ly, 4, 34, 4, segments=16)
lidar_mesh.add_box(cx=0, cy=0, cz=36, dx=70, dy=70, dz=4)
lidar_mesh.write_stl("stl_files/lidar_mount.stl")

# 5. Full Robot Assembly STL
full_mesh = STLMesh("Full_Robot_Chassis")
full_mesh.triangles.extend(bottom_mesh.triangles)

for sx, sy in [(50, 60), (-50, 60), (50, -60), (-50, -60)]:
    full_mesh.add_cylinder(cx=sx, cy=sy, z_bottom=6, z_top=46, radius=3.5, segments=16)

for norm, v1, v2, v3 in top_mesh.triangles:
    full_mesh.triangles.append((norm, (v1[0], v1[1], v1[2] + 46), (v2[0], v2[1], v2[2] + 46), (v3[0], v3[1], v3[2] + 46)))

for mx in [-45, 45]:
    for norm, v1, v2, v3 in motor_mesh.triangles:
        full_mesh.triangles.append((norm, (v1[0] + mx, v1[1], v1[2] + 4), (v2[0] + mx, v2[1], v2[2] + 4), (v3[0] + mx, v3[1], v3[2] + 4)))

for norm, v1, v2, v3 in lidar_mesh.triangles:
    full_mesh.triangles.append((norm, (v1[0], v1[1] + 30, v1[2] + 50), (v2[0], v2[1] + 30, v2[2] + 50), (v3[0], v3[1] + 30, v3[2] + 50)))

full_mesh.write_stl("stl_files/full_robot_chassis.stl")
print("All STL files regenerated successfully with zero-collision cutouts!")
